language : cpp
dist: trusty
env:
  - CC=gcc-6 CXX=g++-6
addons:
  apt:
    packages:
    - valgrind
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
compiler:
  - gcc
before_install:
    - export CC=gcc-6
    - export CXX=g++-6
    - ${CXX} --version
    - export GOPATH=`pwd`/gosrc
    - export PATH=`pwd`/gosrc/bin:$PATH
    - go get qpm.io/qpm
    - sh -e /etc/init.d/xvfb start
script:
    - git clone https://github.com/benlau/qtci.git
    - source qtci/path.env
    - qt-5.7
    - source qt-5.7.env
    - qmake
    - make
    - APP=`find . -name tests`
    - $APP

