language : cpp
dist: trusty
env:
  - DISPLAY=:99.0
addons:
  apt:
    packages:
    - valgrind
compiler:
  - gcc
before_install:
    - sudo apt-get install -qq g++-6
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
    - export GOPATH=`pwd`/gosrc
    - export PATH=`pwd`/gosrc/bin:$PATH
    - go get qpm.io/qpm
    - sh -e /etc/init.d/xvfb start
script:
    - git clone https://github.com/benlau/qtci.git
    - source qtci/path.env
    - qt-5.7
    - source qt-5.7.env
    - qmake
    - make
    - APP=`find . -name tests`
    - $APP

