language : cpp
dist: trusty
env:
  - DISPLAY=:99.0
addons:
  apt:
    packages:
    - valgrind
compiler:
  - gcc
before_install:
    - export GOPATH=`pwd`/gosrc
    - export PATH=`pwd`/gosrc/bin:$PATH
    - go get qpm.io/qpm
    - sh -e /etc/init.d/xvfb start
script:
    - git clone https://github.com/benlau/qtci.git
    - source qtci/path.env
    - qt-5.7
    - source qt-5.7.env
    - mkdir build
    - cd build
    - run-unittests ../tests/unittests/unittests.pro

