version: build{build}

branches:
  except:
    - project/travis

environment:
  matrix:
  - name: win32
    platform: amd64_x86
    qt: msvc2017
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set GOPATH=c:\gopath
  - set QTDIR=C:\Qt\5.9.7\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;%GOPATH%\bin;
  - go get qpm.io/qpm
  - go install qpm.io/qpm
  - dir %GOPATH%\bin
  - cd tests
  - qpm install
  - cd ..
  - qmake 
  - nmake
  - dir /w
  - tests\c11tests\release\c11tests
  - tests\c14tests\release\c14tests
  - tests\c17tests\release\c17tests
  - tests\quicktests\release\quicktests
  - tests\noqttests\release\noqttests
  - tests\builder\release\builder
  - type build_log.txt
  - npm install
  - npm run collect_compiler_error

